# Build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Final stage
FROM alpine:latest
RUN apk add --no-cache ca-certificates nginx

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/dist .
COPY frontend/nginx.conf /etc/nginx/nginx.conf

# Nginx needs this directory
RUN mkdir -p /run/nginx

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
