# Build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# Final stage
FROM nginx:alpine
RUN apk add --no-cache ca-certificates

WORKDIR /
COPY frontend/nginx.conf /etc/nginx/nginx.conf
COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && sed -i 's/\r$//' /entrypoint.sh

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/dist .

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
